INSERT 
	INTO PAYMENT(ID, STATUS, AMOUNT)
	VALUES ('70042', 'NEW', 7659);

INSERT 
	INTO PAYMENT(ID, STATUS, AMOUNT)
	VALUES ('70043', 'NEW', 9900);

INSERT 
	INTO PAYMENT(ID, STATUS, AMOUNT)
	VALUES ('70044', 'COMPLETED', 4549);

INSERT 
	INTO TRANSACTION(ID, ACTIVE, CONTACT_EMAIL, CONTACT_PERSON, PAYMENT_ID)
	VALUES ('2000042S', 'FALSE', 'alan@customers.com', 'Alan', '70042');

INSERT 
	INTO TRANSACTION(ID, ACTIVE, CONTACT_EMAIL, CONTACT_PERSON, PAYMENT_ID)
	VALUES ('2000043S', 'TRUE', 'alan@customers.com', 'Alan', '70042');

INSERT 
	INTO TRANSACTION(ID, ACTIVE, CONTACT_EMAIL, CONTACT_PERSON, PAYMENT_ID)
	VALUES ('2000044K', 'TRUE', 'bob@customers.com', 'Bob', '70043');

INSERT 
	INTO TRANSACTION(ID, ACTIVE, CONTACT_EMAIL, CONTACT_PERSON, PAYMENT_ID)
	VALUES ('2000045G', 'TRUE', 'bob@customers.com', 'Bob', '70043');

INSERT 
	INTO TRANSACTION(ID, ACTIVE, CONTACT_EMAIL, CONTACT_PERSON, PAYMENT_ID)
	VALUES ('2000046G', 'TRUE', 'charile@customers.com', 'Charile', '70044');

INSERT 
	INTO ORDERS(ID, STATUS, TOTAL, EMAIL, FULL_NAME)
	VALUES ('6789', 'PENDING', 12340, 'alan@customers.com', 'Alan');
	
INSERT 
	INTO ORDERS(ID, STATUS, TOTAL, EMAIL, FULL_NAME)
	VALUES ('6790', 'CANCELLED', 299, 'alan@customers.com', 'Alan');
	
INSERT 
	INTO ORDERS(ID, STATUS, TOTAL, EMAIL, FULL_NAME)
	VALUES ('6791', 'COMPLETED', 10000, 'bob@customers.com', 'Bob');

INSERT 
	INTO ORDERS(ID, STATUS, TOTAL, EMAIL, FULL_NAME)
	VALUES ('6792', 'PENDING', 10000, 'charlie@customers.com', 'Charile');

INSERT 
	INTO ORDERS(ID, STATUS, TOTAL, EMAIL, FULL_NAME)
	VALUES ('6793', 'PENDING', 10000, 'dana@customers.com', 'Dana');
